name: Gitee repos mirror periodic job

on:
  push:
  watch:
    types: started
  schedule:
    - cron: "0 23 * * *"

jobs:
  dext7r:
    name: dext7r
    runs-on: ubuntu-latest
    steps:
      - name: dext7r
        uses: Yikun/hub-mirror-action@v1.0
        with:
          src: github/dext7r
          dst: gitee/dext7r
          dst_key: ${{ secrets.PRIVATE_KEY }}
          dst_token: ${{ secrets.TOKEN }}
          account_type: org
          timeout: "1h"
          debug: true
          force_update: true
